common:
    lidar_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"
    image_topic:  "/camera/image_color"
    image_type:  RGB8    # 1 RGB8   2 COMPRESSED
    gravity_acc: [ 0.0, 0.0, 9.7833 ]
    
lidar_parameter:
    lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,  4 for Robosense LiDAR, 5 for HESAI-Pandar LiDAR
    N_SCANS: 6
    SCAN_RATE: 10                # only need to be set for velodyne, unit: Hz,
    time_unit: 3            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.

imu_parameter:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    time_diff_enable: false
    
camera_parameter:
    image_width: 1280
    image_height: 1024
    image_resize_ratio: 0.5
    camera_intrinsic: [ 863.4241, 0.0, 640.6808,
                        0.0, 863.4171, 518.3392,
                        0.0, 0.0, 1.0 ]
    camera_dist_coeffs: [ -0.1080, 0.1050, -1.2872e-04, 5.7923e-05, -0.0222 ]  #k1, k2, p1, p2, k3

extrinsic_parameter:
    extrinsic_enable:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_t_imu_lidar: [ 0.0, 0.0, 0.0 ]
    extrinsic_R_imu_lidar: [ 1, 0, 0, 
                             0, 1, 0, 
                             0, 0, 1 ]
    extrinsic_t_imu_camera: [ 0.050166, 0.0474116, -0.0312415 ]
    extrinsic_R_imu_camera: [ -0.00113207, -0.0158688, 0.999873,
                              -0.9999999, -0.000486594, -0.00113994,
                             0.000504622, -0.999874, -0.0158682 ]
